-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 22:30:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema event_page
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema event_page
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `event_page` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `event_page` ;

-- -----------------------------------------------------
-- Table `event_page`.`categoriaevento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_page`.`categoriaevento` ;

CREATE TABLE IF NOT EXISTS `event_page`.`categoriaevento` (
  `id_catevento` INT NOT NULL AUTO_INCREMENT,
  `nombre_catevento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_catevento`),
  UNIQUE INDEX `id_catevento_UNIQUE` (`id_catevento` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`invitado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_page`.`invitado` ;

CREATE TABLE IF NOT EXISTS `event_page`.`invitado` (
  `id_invitado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `biografia` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_invitado`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_page`.`evento` ;

CREATE TABLE IF NOT EXISTS `event_page`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nombre_evento` VARCHAR(45) NULL DEFAULT NULL,
  `costo` DOUBLE NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `capacidad` INT NULL DEFAULT NULL,
  `id_categoria` INT NULL DEFAULT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `id_invitado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`),
  UNIQUE INDEX `id_evento_UNIQUE` (`id_evento` ASC) VISIBLE,
  INDEX `fk_evento_eventcat_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_evento_invitado_idx` (`id_invitado` ASC) VISIBLE,
  CONSTRAINT `fk_evento_eventcat`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `event_page`.`categoriaevento` (`id_catevento`),
  CONSTRAINT `fk_evento_invitado`
    FOREIGN KEY (`id_invitado`)
    REFERENCES `event_page`.`invitado` (`id_invitado`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_page`.`usuario` ;

CREATE TABLE IF NOT EXISTS `event_page`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `dni` INT NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `contraseña` VARCHAR(45) NULL DEFAULT NULL,
  `admin` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
