-- MySQL Script generated by MySQL Workbench
-- Fri Dec  1 09:22:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema event_page
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema event_page
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `event_page` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `event_page` ;

-- -----------------------------------------------------
-- Table `event_page`.`categoria_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_page`.`categoria_evento` (
  `id_categoria_evento` INT NOT NULL AUTO_INCREMENT,
  `nombre_catevento` VARCHAR(45) NOT NULL,
  `eliminado` TINYINT NOT NULL,
  PRIMARY KEY (`id_categoria_evento`),
  UNIQUE INDEX `id_catevento_UNIQUE` (`id_categoria_evento` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_page`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL DEFAULT NULL,
  `apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `dni` INT NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(150) NULL DEFAULT NULL,
  `admin` TINYINT NULL DEFAULT NULL,
  `eliminado` TINYINT NOT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_page`.`tarjeta` (
  `id_tarjeta` INT NOT NULL AUTO_INCREMENT,
  `nombre_propietario` VARCHAR(150) NOT NULL,
  `numero_tarjeta` VARCHAR(16) NOT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `id_usuario` INT NOT NULL,
  `eliminado` TINYINT NOT NULL,
  PRIMARY KEY (`id_tarjeta`),
  INDEX `FK_TARJETA_USUARIO_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK_TARJETA_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `event_page`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_page`.`compra` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `id_tarjeta` INT NULL DEFAULT NULL,
  `fecha_compra` DATETIME NULL DEFAULT NULL,
  `pendiente` TINYINT NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `FK_COMPRA_TARJETA_idx` (`id_tarjeta` ASC) VISIBLE,
  INDEX `FK_COMPRA_USUARIO_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK_COMPRA_TARJETA`
    FOREIGN KEY (`id_tarjeta`)
    REFERENCES `event_page`.`tarjeta` (`id_tarjeta`),
  CONSTRAINT `FK_COMPRA_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `event_page`.`usuario` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`configuracion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_page`.`configuracion` (
  `id_configuracion` INT NOT NULL AUTO_INCREMENT,
  `parametro` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_configuracion`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`invitado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_page`.`invitado` (
  `id_invitado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `biografia` LONGTEXT NOT NULL,
  `eliminado` TINYINT NOT NULL,
  `imagen_url` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_invitado`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_page`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nombre_evento` VARCHAR(45) NULL DEFAULT NULL,
  `costo` DOUBLE NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `capacidad` INT NULL DEFAULT NULL,
  `id_categoria_evento` INT NULL DEFAULT NULL,
  `descripcion` VARCHAR(300) NULL DEFAULT NULL,
  `id_invitado` INT NULL DEFAULT NULL,
  `eliminado` VARCHAR(45) NOT NULL,
  `destacado` TINYINT NULL DEFAULT NULL,
  `imagen_url` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`id_evento`),
  UNIQUE INDEX `id_evento_UNIQUE` (`id_evento` ASC) VISIBLE,
  INDEX `fk_evento_eventcat_idx` (`id_categoria_evento` ASC) VISIBLE,
  INDEX `fk_evento_invitado_idx` (`id_invitado` ASC) VISIBLE,
  CONSTRAINT `fk_evento_eventcat`
    FOREIGN KEY (`id_categoria_evento`)
    REFERENCES `event_page`.`categoria_evento` (`id_categoria_evento`),
  CONSTRAINT `fk_evento_invitado`
    FOREIGN KEY (`id_invitado`)
    REFERENCES `event_page`.`invitado` (`id_invitado`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `event_page`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_page`.`detalle_compra` (
  `id_detalle_compra` INT NOT NULL AUTO_INCREMENT,
  `id_compra` INT NOT NULL,
  `id_evento` INT NOT NULL,
  PRIMARY KEY (`id_detalle_compra`),
  INDEX `FK_DETALLE_COMPRA_idx` (`id_compra` ASC) VISIBLE,
  INDEX `FK_DETALLE_COMPRA_EVENTO_idx` (`id_evento` ASC) VISIBLE,
  CONSTRAINT `FK_DETALLE_COMPRA`
    FOREIGN KEY (`id_compra`)
    REFERENCES `event_page`.`compra` (`id_compra`),
  CONSTRAINT `FK_DETALLE_COMPRA_EVENTO`
    FOREIGN KEY (`id_evento`)
    REFERENCES `event_page`.`evento` (`id_evento`))
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
